DROP DATABASE IF EXISTS sneakerness;
CREATE DATABASE sneakerness;
USE sneakerness;

CREATE TABLE Organisator (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Naam VARCHAR(50) NOT NULL,
    Gebruikersnaam VARCHAR(30) UNIQUE NOT NULL,
    Wachtwoord VARCHAR(255) NOT NULL,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Bezoeker (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Naam VARCHAR(50) NOT NULL,
    Emailadres VARCHAR(100) UNIQUE NOT NULL,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Evenement (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Naam VARCHAR(100) NOT NULL,
    Datum DATE NOT NULL,
    Locatie VARCHAR(100) NOT NULL,
    AantalTicketsPerTijdslot INT NOT NULL,
    BeschikbareStands INT NOT NULL,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Prijs (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Datum DATE NOT NULL,
    Tijdslot VARCHAR(20) NOT NULL,
    Tarief DECIMAL(6,2) NOT NULL,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Ticket (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    BezoekerId INT NOT NULL,
    EvenementId INT NOT NULL,
    PrijsId INT NOT NULL,
    AantalTickets INT NOT NULL,
    Datum DATE NOT NULL,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (BezoekerId) REFERENCES Bezoeker(Id),
    FOREIGN KEY (EvenementId) REFERENCES Evenement(Id),
    FOREIGN KEY (PrijsId) REFERENCES Prijs(Id)
);

CREATE TABLE Verkoper (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Naam VARCHAR(75) NOT NULL,
    SpecialeStatus BOOLEAN DEFAULT FALSE,
    VerkooptSoort VARCHAR(50) NOT NULL,
    StandType ENUM('A', 'AA', 'AA+') NOT NULL,
    Dagen ENUM('Eén dag', 'Twee dagen') NOT NULL,
    Logo VARCHAR(255),
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Stand (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    VerkoperId INT NOT NULL,
    StandType ENUM('A', 'AA', 'AA+') NOT NULL,
    Prijs DECIMAL(8,2) NOT NULL,
    VerhuurdStatus BOOLEAN DEFAULT FALSE,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (VerkoperId) REFERENCES Verkoper(Id)
);

CREATE TABLE Contactpersoon (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Naam VARCHAR(50) NOT NULL,
    Telefoonnummer VARCHAR(15),
    Emailadres VARCHAR(100) UNIQUE NOT NULL,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ContactPerVerkoper (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    VerkoperId INT NOT NULL,
    ContactpersoonId INT NOT NULL,
    IsActief BOOLEAN DEFAULT TRUE,
    Opmerking VARCHAR(255),
    DatumAangemaakt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DatumGewijzigd TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (VerkoperId) REFERENCES Verkoper(Id),
    FOREIGN KEY (ContactpersoonId) REFERENCES Contactpersoon(Id)
);
